---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devstats-volume
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Gi
  nfs:
    # This should be the name of the fileshare in cloud filestore
    path: /devstats_knative
    server: 10.54.105.58
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devstats-claim
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-storage
  volumeName: devstats-volume
